version: '3'
services:

  dbr_postgres:
    image: postgres:11.5-alpine
    hostname: dbr_postgres
    container_name: dbr_postgres
    restart: always
    volumes:
# The previws line will be added at the docker-compose_preprod.yml file (non preprod)
#      - DbDev:/var/lib/postgresql/data
# the prevews line will be commentat at docker-compose_preprod.yml file
      - ./PostgresPREPROD/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-drf