services:

  outgi:
    hostname: outgi
    container_name: outgi
    build: .
    user: pilot
    restart: always
    volumes:
      - "./database:/DashboardRaffinerie/database"
    working_dir: /DashboardRaffinerie
    env_file: .env
    networks:
      - frontend
#      - backend-drf
    command: "bash ./launcher_prod.sh"
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.alon_nginx.tls.certresolver=myresolver
      - traefik.http.routers.alon_nginx.rule=Host(`$DOMAIN`)

  networks:
    frontend:
      name: 'frontend'
      external: true
