services:

  outgi:
    hostname: outgi
    container_name: outgi
    build: .
    user: pilot
    restart: always
    volumes:
      - "./database:/DashboardRaffinerie/database"
    working_dir: /DashboardRaffinerie
    env_file: .env
    networks:
      - frontend
#      - backend
    command: "bash start.sh"
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.alon_nginx.tls.certresolver=myresolver
      - traefik.http.routers.alon_nginx.rule=Host(`$DOMAIN`)
      - traefik.http.services.test_machine.loadbalancer.server.port=8080

networks:
  frontend:
    name: "frontend"
    external: true