# Generated by Django 4.2.17 on 2025-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='garant_du_cadre',
            field=models.BooleanField(default=False, verbose_name='Garant du cadre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='presta_interne',
            field=models.BooleanField(default=False, verbose_name='Presta interne'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_budg',
            field=models.BooleanField(default=False, verbose_name='Référent budget / subvention'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_tache',
            field=models.BooleanField(default=False, verbose_name='Référent tâche planning'),
        ),
    ]
