# Generated by Django 4.2.17 on 2025-01-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0002_customuser_garant_du_cadre_customuser_presta_interne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
    ]
