from python:3.10-bullseye

RUN apt update
RUN apt upgrade -y

RUN mkdir -p /usr/share/man/man1
RUN mkdir -p /usr/share/man/man7
RUN apt-get install -y --no-install-recommends postgresql-client

RUN apt-get install -y nano iputils-ping curl borgbackup cron

RUN useradd -ms /bin/bash user1
USER user1

RUN curl -sSL https://install.python-poetry.org | python3 -

#COPY poetry.lock pyproject.toml /alon/
WORKDIR /DashboardRaffinerie

RUN export PATH="/home/user1/.local/bin:$PATH"
#RUN /home/alon/.local/bin/poetry install --no-root --no-ansi --without dev


