# Generated by Django 4.2.4 on 2024-01-07 14:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountAnalyticAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_odoo', models.SmallIntegerField()),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAnalyticGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('iban', models.CharField(max_length=150, unique=True, verbose_name='Iban')),
                ('bic', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bic ou Swift')),
                ('currency', models.CharField(default='euro', max_length=15, verbose_name='Devise')),
                ('account_number', models.CharField(max_length=150, unique=True, verbose_name='Le numéro de compte')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qonto_login', models.CharField(max_length=100)),
                ('qonto_apikey', models.CharField(max_length=200)),
                ('odoo_url', models.URLField()),
                ('odoo_login', models.CharField(max_length=100)),
                ('odoo_apikey', models.CharField(max_length=200)),
                ('odoo_dbname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_odoo', models.SmallIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('M', 'membership'), ('B', 'beneficiarie')], default='B', max_length=1)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('structure', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('image', stdimage.models.JPEGField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(960, 540)], variations={'med': (960, 540), 'thumb': (270, 270, True)}, verbose_name='Image du contact')),
                ('badge', models.ManyToManyField(blank=True, related_name='contacts', to='dashboard_app.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nom du group')),
                ('second_num_analytic_code', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Deuxièm nombre du code analytique')),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nom du pôle')),
                ('first_numbers_analytic_code', models.CharField(choices=[('10', 'Dix'), ('20', 'Vingt'), ('30', 'Trent'), ('40', 'Quarante'), ('60', 'Cinquante'), ('70', 'Soixante-dix'), ('80', 'Quatre-vingts'), ('90', 'Quatre vingt')], max_length=2, verbose_name='Choix des de premier nombres du code analytique')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nom du projet')),
                ('last_num_analytic_code', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Dernière nombre du code analytique')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.pole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.pole'),
        ),
        migrations.CreateModel(
            name='DepensesBienveillance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('proposition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valide', models.BooleanField(default=False)),
                ('facture', models.BooleanField(default=False)),
                ('paye', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('account_analytic_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.accountanalyticgroup')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.contact')),
            ],
        ),
    ]
