# Generated by Django 4.2.4 on 2024-01-15 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='dashboard_app.pole', verbose_name='Pôle'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='previsioncost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prevision_cost', to=settings.AUTH_USER_MODEL, verbose_name='Intitulé'),
        ),
        migrations.AddField(
            model_name='pole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poles', to='dashboard_app.group', verbose_name='Groupe'),
        ),
        migrations.AddField(
            model_name='pole',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='analytic_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Organigrame', to='dashboard_app.accountanalyticaccount', verbose_name='Compte analytique'),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organigrame', to='dashboard_app.role', verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organigrame', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='internservicecaring',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intern_service_caring', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='grant',
            name='analytic_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Grant', to='dashboard_app.accountanalyticaccount', verbose_name='Compte analytique'),
        ),
        migrations.AddField(
            model_name='depensesbienveillance',
            name='account_analytic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.accountanalyticgroup'),
        ),
        migrations.AddField(
            model_name='depensesbienveillance',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='badge',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='dashboard_app.badge'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='dashboard_app.project'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='accountanalyticaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.accountanalyticgroup'),
        ),
    ]
