# Generated by Django 4.2.4 on 2024-01-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisionCost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('CAR', 'bienveillance'), ('IN_S', 'prestation interne'), ('EX_S', 'Prestation externe'), ('SP_I', 'Dépense interne'), ('SUB', 'Subvention'), ('SER', 'Prestation'), ('S', 'Vente'), ('IN_R', 'Récette interne')], default='CAR', max_length=4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prevision_cost', to=settings.AUTH_USER_MODEL, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name': 'Prévisionnel',
            },
        ),
    ]
