# Generated by Django 4.2.4 on 2024-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
