# Generated by Django 4.2.4 on 2024-02-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='reveree',
            new_name='referee',
        ),
    ]
