# Generated by Django 4.2.4 on 2024-01-31 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realcost',
            options={'verbose_name': 'Bienvillance où Préstation interne', 'verbose_name_plural': 'Bienvillances où Préstation internes'},
        ),
        migrations.RemoveField(
            model_name='realcost',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='realcost',
            name='titeld',
        ),
        migrations.CreateModel(
            name='RealCostInternSpending',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='montant')),
                ('date', models.DateField()),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_cost_intern_spending', to='dashboard_app.pole', verbose_name='pôle')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_cost_intern_spending', to='dashboard_app.cost', verbose_name='type')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='RealCostExternService',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=50, verbose_name='Fourniseur')),
                ('titeld', models.CharField(max_length=60, verbose_name='intitulé')),
                ('date', models.DateField()),
                ('validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('payed', models.BooleanField(default=False, verbose_name='Payé')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_cost_extern_service', to='dashboard_app.cost', verbose_name='type')),
            ],
            options={
                'verbose_name': 'Préstation externe / achat',
                'verbose_name_plural': 'Préstations externes / achats',
            },
        ),
    ]
