# Generated by Django 4.2.4 on 2024-02-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poles', to='dashboard_app.groupe', verbose_name='Groupe'),
        ),
    ]
