# Generated by Django 4.2.4 on 2023-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_badge_contact_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id_odoo',
            field=models.SmallIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('M', 'membership'), ('B', 'beneficiarie')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
