# Generated by Django 4.2.4 on 2024-02-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_pole_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestationsventsrecettesint',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='dashboard_app.groupe', verbose_name='groupe'),
        ),
    ]
