# Generated by Django 4.2.4 on 2024-01-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_realcost_options_remove_realcost_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsioncost',
            old_name='titeld',
            new_name='titled',
        ),
        migrations.RenameField(
            model_name='realcostexternservice',
            old_name='titeld',
            new_name='titled',
        ),
    ]
