# Generated by Django 4.2.4 on 2024-02-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_rename_reveree_grant_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='type',
            field=models.CharField(choices=[('CAR', 'bienveillance'), ('IN_S', 'prestation interne'), ('EX_S', 'Prestation externe'), ('SP_I', 'Dépense interne'), ('SUB', 'Subvention'), ('SER', 'Prestation'), ('S', 'Vente'), ('IN_R', 'Récette interne')], default='CAR', max_length=4, verbose_name='Categorie de dépense'),
        ),
    ]
