# Generated by Django 4.2.4 on 2024-04-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_transaction_attachment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='attachment_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment_ids',
            field=models.TextField(blank=True, default=[]),
        ),
    ]
