# Generated by Django 4.2.4 on 2024-02-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_rename_titeld_previsioncost_titled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='realcostinternspending',
            options={'verbose_name': 'Dépense réele interne', 'verbose_name_plural': 'Dépenses réeles internes'},
        ),
    ]
