# Generated by Django 4.2.4 on 2024-02-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0005_alter_cost_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'verbose_name': 'Organigrame'},
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='budget_referee',
            field=models.BooleanField(default=False, verbose_name='référent budget / subvention'),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='intern_services',
            field=models.BooleanField(default=False, verbose_name='presta interne'),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='settlement_agent',
            field=models.BooleanField(default=False, verbose_name='garant du cadre'),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='task_planning_referee',
            field=models.BooleanField(default=False, verbose_name='référent tâche planning'),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organigrame', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
    ]
