# Generated by Django 4.2.4 on 2024-01-11 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0005_alter_action_uuid_alter_contact_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalChart',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analytic_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Organigrame', to='dashboard_app.accountanalyticaccount', verbose_name='Compte analytique')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organigrame', to='dashboard_app.role', verbose_name='Rôle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organigrame', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Organigrame',
                'verbose_name_plural': 'Organigrames',
            },
        ),
    ]
