# Generated by Django 4.2.4 on 2024-02-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0006_alter_organizationalchart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalchart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organigrame', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
    ]
