# Generated by Django 4.2.4 on 2023-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='odoo_apikey',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='qonto_apikey',
            field=models.CharField(max_length=200),
        ),
    ]
