# Generated by Django 4.2.4 on 2023-10-03 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_alter_contact_email_alter_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountanalyticaccount',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
