# Generated by Django 4.2.4 on 2023-11-01 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_accountaccount_accountjournal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensesBienveillance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('proposition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valide', models.BooleanField(default=False)),
                ('facture', models.BooleanField(default=False)),
                ('paye', models.BooleanField(default=False)),
                ('account_analytic_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.accountanalyticgroup')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.contact')),
            ],
        ),
    ]
