# Generated by Django 4.2.4 on 2023-11-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_depensesbienveillance'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensesbienveillance',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
