# Generated by Django 4.2.4 on 2023-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_depensesbienveillance_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensesbienveillance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
